version: "3"

volumes:
  wdf-db-data:
  wdf-api-sync:
    external: true

services:
  db:
    image: "postgres:10.5"
    volumes:
      - wdf-db-data:/var/lib/postgresql/data
  memcached:
    image: memcached:alpine
    command: "memcached -m 500 -I 2m"
  api:
    image: wdf/api:dev
    env_file:
      - .env_api_dev
    command: sh bin/start
    volumes:
      - "wdf-api-sync:/app/api:nocopy"
      - /app/api/tmp
    ports:
      - "3031:3000"
    depends_on:
      - "db"
      - "memcached"
  specs:
    image: wdf/api:test
    command: tail -f /dev/null
    env_file:
      - .env_api_test
    volumes:
      - "wdf-api-sync:/app/api:nocopy"
      - /app/api/tmp
    depends_on:
      - "db"
      - "memcached"
