# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Install dependent libraries
      run: sudo apt-get install libpq-dev
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load
      env:
        RAILS_ENV: test
        DB_ADAPTER: postgresql
        DB_USER: postgres
        DB_HOST: localhost
        DB_PASSWORD: postgres
        DB_NAME: postgres
    - name: Run RSpec
      run: COVERAGE=true bundle exec rspec
      env:
        RAILS_ENV: test
        DB_ADAPTER: postgresql
        DB_USER: postgres
        DB_HOST: localhost
        DB_PASSWORD: postgres
        DB_NAME: postgres
